/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(DMO_burst_extract.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c9afdc220da1c42b58daeb33dc5919c0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/DMO_TETRA/DMO_burst_extract.h>
// pydoc.h is automatically generated in the build directory
#include <DMO_burst_extract_pydoc.h>

void bind_DMO_burst_extract(py::module& m)
{

    using DMO_burst_extract    = ::gr::DMO_TETRA::DMO_burst_extract;


    py::class_<DMO_burst_extract, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<DMO_burst_extract>>(m, "DMO_burst_extract", D(DMO_burst_extract))

        .def(py::init(&DMO_burst_extract::make),
           D(DMO_burst_extract,make)
        )
        



        ;

    py::enum_<::gr::DMO_TETRA::OperationMode>(m,"OperationMode")
        .value("DMO", ::gr::DMO_TETRA::OperationMode::DMO) // 1
        .value("TMO", ::gr::DMO_TETRA::OperationMode::TMO) // 0
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::DMO_TETRA::OperationMode>();
    py::enum_<::gr::DMO_TETRA::BurstType>(m,"BurstType")
        .value("INACTIVE", ::gr::DMO_TETRA::BurstType::INACTIVE) // 0
        .value("DSB", ::gr::DMO_TETRA::BurstType::DSB) // 1
        .value("DNB", ::gr::DMO_TETRA::BurstType::DNB) // 2
        .value("DNB_SF", ::gr::DMO_TETRA::BurstType::DNB_SF) // 3
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::DMO_TETRA::BurstType>();



}








