/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(MAC_DECODER_LAYER_2_3.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(35c6dd5ded5d9ef170b23b4b896646e9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/DMO_TETRA/MAC_DECODER_LAYER_2_3.h>
// pydoc.h is automatically generated in the build directory
#include <MAC_DECODER_LAYER_2_3_pydoc.h>

void bind_MAC_DECODER_LAYER_2_3(py::module& m)
{

    using MAC_DECODER_LAYER_2_3    = gr::DMO_TETRA::MAC_DECODER_LAYER_2_3;


    py::class_<MAC_DECODER_LAYER_2_3, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<MAC_DECODER_LAYER_2_3>>(m, "MAC_DECODER_LAYER_2_3", D(MAC_DECODER_LAYER_2_3))

        .def(py::init(&MAC_DECODER_LAYER_2_3::make),
           D(MAC_DECODER_LAYER_2_3,make)
        )
        



        ;




}








